### ISSUE TITLE
[dcc32 Fatal Error] F2084 Internal Error: DBG3198

### ISSUE THREAD

**Issue by talpa** [ezequieljuliano/DelphiLaboratory#1]
Hi, I tried build SpringAndMVC and I have this error final.Why?:) 

Ales

**Comment by ezequieljuliano** [comment]
You have installed and configured the latest versions of DMVC and Spring4D (release 1.2)?

Has this link Embarcadero that can help you: http://docwiki.embarcadero.com/RADStudio/Seattle/en/F2084_Internal_Error_-_%25s%25d_(Delphi)

**Comment by talpa** [comment]
Yes I have,I have the same problem in other project with TSession,

**Comment by egroups** [comment]
I have same problem with today Spring release/1.2 without DMVC.In Debug mode I get this error,in Release mode compiled ok.Delphi XE6

**Comment by sglienke** [comment]
This is an error in the compiler (reported as https://quality.embarcadero.com/browse/RSP-14974)
The circumstances to cause this are listed in my comment on that issue.

If you follow my recommendation to build Spring4D and then only point to the dcu directory instead of adding the source directories to the library or search path it will not appear as far as I know.
However I removed the inline from the TCollections.Create\* methods as they did not have much of a beneficial effect anyway so this error should be gone once you update to the latest commit in release/1.2

**Comment by ezequieljuliano** [comment]
Thank you for response Stefan. Very enlightening.
